# Title of your blog; shows in the header


name: "Ted Hart"
subname: "ecologist / data scientist / developer "

# Description of your content (will only be used on Google Search)
description: "blog about data science, ecology, informatics, programming, data"

# Your name. Will show in your footer + sidebar
author: "Ted Hart"
email: "emh@emhart.info"

date_format: "ordinal"

url: "http://emhart.info"
root: /

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "I’m a senior data scientist in silicon valley and adjunct faculty at the University of Vermont. I build things for data: things that process it, parse it, visualize it, and analyze it. I like my beer cold, my snow deep, my mountains high, and my data open. I am a recovering academic."

# Social Accounts (mine, as placeholders)

twitter: emhrt_
github: emhart
linkedin: 152649359
impactstory: EdmundHart
orcid: 0000-0001-7367-7969

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain: emhart.info
ga_tracking_id: UA-48098407-1

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: redcarpet
highlighter: pygments

permalink: /blog/:year/:month/:day/:title/
#highlighter: pygments

paginate: 8
paginate_path: "/page/:num"
relative_permalinks: false



# Disqus Comments
disqus_short_name: distributedecology
disqus_show_comment_count: false


# SCSS

sass:
  sass_dir: _scss
  style: :compressed
